import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faPlane,
  faMoon,
  faFutbol,
  faFootballBall,
  faMicrophoneAlt,
} from '@fortawesome/free-solid-svg-icons';

import { ReactComponent as CroixOccitane } from '../assets/icons/croix_occitane.svg';
import { ReactComponent as Cemetery } from '../assets/icons/cemetery.svg';

import {
  Network, Line, Station, LineType, WalkTo,
} from './lines';

export * from './colors';

export const network = Network(
  // ==================== METRO ====================
  Line(
    LineType.METRO,
    'A',
    { shape: 'square', background: '#E51A23' },
    Station('Basso Cambo'),
    Station('Bellefontaine'),
    Station('Reynerie'),
    Station('Mirail Université'),
    Station('Bagatelle'),
    Station('Mermoz'),
    Station('Fontaine-Lestang'),
    Station('Arènes', null, WalkTo('Saint-Cyprien Arènes')),
    Station('Patte d\'Oie'),
    Station('Saint-Cyprien République'),
    Station('Esquirol'),
    Station('Capitole'),
    Station('Jean Jaurès'),
    Station('Marengo SNCF', null, WalkTo('Matabiau Gare SNCF')),
    Station('Jolimont'),
    Station('Roseraie'),
    Station('Argoulets'),
    Station('Balma Gramont'),
  ),

  Line(
    LineType.METRO,
    'B',
    { shape: 'square', background: '#FFDC01', foreground: '#212121' },
    Station('Borderouge'),
    Station('Trois Cocus'),
    Station('La Vache'),
    Station('Barrière de Paris'),
    Station('Minimes Claude Nougaro'),
    Station('Canal du Midi'),
    Station('Compans-Caffarelli'),
    Station('Jeanne d\'Arc'),
    Station('Jean Jaurès'),
    Station('François Verdier'),
    Station('Carmes'),
    Station('Palais de Justice'),
    Station('Saint-Michel Marcel Langer'),
    Station('Empalot'),
    Station('Saint-Agne SNCF'),
    Station('Saouzelong'),
    Station('Rangueil'),
    Station('Faculté de Pharmacie'),
    Station('Université Paul Sabatier'),
    Station('Ramonville'),
    // Station('Parc Technologique du Canal'),
  ),

  // Line(
  //   LineType.METRO,
  //   '3',
  //   { shape: 'square', background: '#D05B1D' },
  //   Station('Colomiers Gare', null, WalkTo('Colomiers Gare SNCF')),
  //   Station('Airbus Colomiers'),
  //   Station('Airbus Saint-Martin'),
  //   Station('Jean Maga' /* TODO: Arrêts T1 T2 */),
  //   Station('Sept Deniers', null, WalkTo('Sept Deniers', 'Salvador Dali')),
  //   Station('Boulevard de Suisse'),
  //   Station('Fondeyre'),
  //   Station('La Vache', 'Gare', WalkTo('La Vache')),
  //   Station('Toulouse-Lautrec'),
  //   Station('Raynal'),
  //   Station('Bonnefoy'),
  //   Station('Marengo - Matabiau', null, WalkTo('Marengo SNCF'), WalkTo('Matabiau Gare SNCF')),
  //   Station('François Verdier'),
  //   Station('Jean Rieux'),
  //   Station('Côte Pavée'),
  //   Station('L\'Ormeau'),
  //   Station('Montaudran', 'Gare'),
  //   Station('Airbus Defence & Space'),
  //   Station('INPT'),
  //   Station('Enova'),
  //   Station('Labège - La Cadène'),
  // ),

  // ==================== TRAM ====================
  Line(
    LineType.TRAM,
    'T1',
    { shape: 'square', background: '#004A8D' },
    Station('Palais de Justice'),
    Station('Île du Ramier'),
    Station('Fer à Cheval'),
    Station('Avenue de Muret', 'Marcel Cavaillé'),
    Station('Croix de Pierre'),
    Station('Déodat de Séverac'),
    Station('Arènes', null, WalkTo('Saint-Cyprien Arènes')),
    Station('Zénith'),
    Station('Cartoucherie'),
    Station('Casselardit'),
    Station('Purpan'),
    Station('Arènes Romaines'),
    Station('Ancely'),

    Station('Servanty', 'Airbus'),
    Station('Guyenne Berry'),
    Station('Pasteur', 'Mairie de Blagnac'),
    Station('Place du Relais'),
    Station('Odyssud - Ritouret'),
    Station('Patinoire Barradels'),
    Station('Grand Noble'),
    Station('Place Georges Brassens'),
    Station('Andromède - Lycée'),
    Station('Beauzelle'),
    Station('Aéroconstellation'),
    // Station('Parc des Expositions'),
  ),

  Line(
    LineType.TRAM,
    'T2',
    { shape: 'square', background: '#069DDC' },
    Station('Palais de Justice'),
    Station('Île du Ramier'),
    Station('Fer à Cheval'),
    Station('Avenue de Muret', 'Marcel Cavaillé'),
    Station('Croix de Pierre'),
    Station('Déodat de Séverac'),
    Station('Arènes', null, WalkTo('Saint-Cyprien Arènes')),
    Station('Zénith'),
    Station('Cartoucherie'),
    Station('Casselardit'),
    Station('Purpan'),
    Station('Arènes Romaines'),
    Station('Ancely'),

    Station('Nadot'),
    Station('Daurat'),
    Station('Aéroport'),
  ),

  // ==================== LINEO ====================
  Line(
    LineType.BUS_RAPID_TRANSIT,
    'L1',
    { shape: 'square', background: '#F26D22' },
    Station('Sept Deniers', 'Salvador Dali'),
    Station('Chemin de Roques'),
    Station('Nougaro'),
    Station('Lully'),
    Station('Soleil d\'Or'),
    Station('Cité Madrid'),
    Station('Fourmi'),
    Station('Suisse'),
    Station('Ponts Jumeaux'),
    Station('Canal de Brienne'),
    Station('Héraclès'),
    Station('Barcelone Leclerc'),
    Station('Leclerc'),
    Station('Compans-Caffarelli'),
    Station('A. Bernard'),
    Station('Concorde'),
    Station('Jeanne d\'Arc'),
    Station('Jean Jaurès'),
    Station('Saint-Georges'),
    Station('François Verdier'),
    Station('Place Dupuy'),
    Station('Port St-Etienne'),
    Station('Acqueduc'),
    Station('Pérignon'),
    Station('Tilleuls'),
    Station('Deltour'),
    Station('Achiary'),
    Station('Mascard'),
    Station('Aubisque'),
    Station('Cité de l\'Hers'),
    Station('Collège JP Vernant'),
    Station('Gymnase de l\'Hers'),
    Station('Aérodrome'),
    Station('Sainte-Anne'),
    Station('Nollet'),
    Station('Ribaute'),
    Station('Clinique La Croix du Sud'),
    Station('Fonsegrives - Entiore'),
  ),

  Line(
    LineType.BUS_RAPID_TRANSIT,
    'L2',
    { shape: 'square', background: '#F26D22' },
    Station('Arènes', null, WalkTo('Saint-Cyprien Arènes')),
    Station('Négogousses'),
    Station('Hippodrome'),
    Station('Brombach'),
    Station('Casteret'),
    Station('Lemire'),
    Station('Grande-Bretagne'),
    Station('Casselardit'),
    Station('Chardonnet'),
    Station('Hôpital Purpan'),
    Station('Centre Commercial Purpan Sud'),
    Station('Flambère'),
    Station('Bisson'),
    Station('Bertier'),
    Station('Bouriette'),
    Station('Jardinerie'),
    Station('Fournier', 'Airbus'),
    Station('Terce', 'Airbus'),
    Station('Jean Petit'),
    Station('Max Fischl'),
    Station('Caulet'),
    Station('Fontaine'),
    Station('Oratoire'),
    Station('Naurouze'),
    Station('Bascule', 'Seycheron'),
    Station('Médiathèque Pavillon Blanc'),
    Station('Colomiers Gare SNCF'),
    Station('Gers'),
    Station('Salle Gascogne'),
    Station('Val d\'Aran'),
    Station('14ème Régiment d\'Infanterie'),
    Station('Champagne'),
    Station('Stade Bendichou'),
    Station('Morbihan'),
    Station('Monturon'),
    Station('Colomiers Lycée International'),
  ),

  Line(
    LineType.BUS_RAPID_TRANSIT,
    'L3',
    { shape: 'square', background: '#F26D22' },
    Station('Arènes', null, WalkTo('Saint-Cyprien Arènes')),
    Station('Négogousses'),
    Station('Hippodrome'),
    Station('Brombach'),
    Station('Pont Rocade'),
    Station('Tissié'),
    Station('Centre Aéré'),
    Station('Église Lardenne'),
    Station('Lardenne'),
    Station('Montagné'),
    Station('Briqueterie'),
    Station('Saint-Exupéry'),
    Station('Centre Commercial Tournefeuille'),
    Station('Montjoie'),
    Station('Les Chênes'),
    Station('Montel'),
    Station('Saint-Pierre'),
    Station('Périgord'),
    Station('Alpilles'),
    Station('Collège Labitrie'),
    Station('Jean Gay'),
    Station('Tournefeuille Lycée'),
    Station('Loti'),
    Station('Prat Dessus'),
    Station('Rivière Basse'),
    Station('Église Plaisance'),
    Station('Plaisance Monestié'),
  ),

  Line(
    LineType.BUS_RAPID_TRANSIT,
    'L6',
    { shape: 'square', background: '#F26D22' },
    Station('Ramonville'),
    Station('Collège André Malraux'),
    Station('8 Mai 1945'),
    Station('Ramonville Sud'),
    Station('Complexe Agricole'),
    Station('Moulin Armand'),
    Station('Grand Chemin'),
    Station('Peupliers'),
    Station('INRA'),
    Station('Les Genêts'),
    Station('Artaud'),
    Station('Verte Prairie'),
    Station('Castanet', 'République'),
    Station('Blum'),
    Station('Peries'),
    Station('Chemin du Carrelet'),
    Station('Castanet-Tolosan'),
  ),

  Line(
    LineType.BUS_RAPID_TRANSIT,
    'L7',
    { shape: 'square', background: '#F26D22' },
    Station('Cours Dillon'),
    Station('Pont Neuf'),
    Station('Esquirol'),
    Station('Boulbonne'),
    Station('François Verdier'),
    Station('Quartier Général'),
    Station('Grand Rond'),
    Station('Jardin des Plantes'),
    Station('Frizac'),
    Station('Demouilles'),
    Station('Crampel'),
    Station('Trois Fours'),
    Station('Dufour'),
    Station('Courrège'),
    Station('Buissonnets'),
    Station('Six Avril'),
    Station('Tahiti'),
    Station('Ormeau'),
    Station('Clinique Languedoc'),
    Station('Bajac'),
    Station('Lafaurie'),
    Station('Montaudran', 'La Rivière'),
    Station('Route de Revel'),
    Station('Malepère'),
    Station('Laure Delerot'),
    Station('Tilleuls'),
    Station('Saint-Orens Centre Commercial'),
  ),

  Line(
    LineType.BUS_RAPID_TRANSIT,
    'L8',
    { shape: 'square', background: '#F26D22' },
    Station('Marengo SNCF', null, WalkTo('Matabiau Gare SNCF')),
    Station('Bachelier'),
    Station('Jean Jaurès'),
    Station('Saint-Georges'),
    Station('François Verdier'),
    Station('Place Dupuy'),
    Station('Périssé'),
    Station('Lanfant'),
    Station('Belle Paule'),
    Station('Leygue'),
    Station('Beau Soleil'),
    Station('Barrau'),
    Station('Glaïeuls'),
    Station('Langevin'),
    Station('Gers - Lartet'),
    Station('Aude'),
    Station('Corraze'),
    Station('Garin'),
    Station('Tahiti'),
    Station('Bréguet'),
    Station('Piste des Géans'),
    Station('Gonin'),
  ),

  Line(
    LineType.BUS_RAPID_TRANSIT,
    'L9',
    { shape: 'square', background: '#F26D22' },
    Station('Empalot'),
    Station('Mouettes'),
    Station('Empalot Sud'),
    Station('Daste'),
    Station('Platanes'),
    Station('Conseil Régional'),
    Station('Chaussée'),
    Station('Garonnette'),
    Station('Quai de Tounis'),
    Station('Pont Neuf'),
    Station('Esquirol'),
    Station('Boulbonne'),
    Station('François Verdier'),
    Station('Saint-Georges'),
    Station('Jean Jaurès'),
    Station('Victor Hugo'),
    Station('Jeanne d\'Arc'),
    Station('Place Roquelaine'),
    Station('Pont Matabiau'),
    Station('Matabiau - Raynal'),
    Station('Arago'),
    Station('Église Bonnefoy'),
    Station('Hauts de Bonnefoy'),
    Station('Sainte-Hélène'),
    Station('Barrière de Croix Daurade'),
    Station('Place Bila'),
    Station('Cazals'),
    Station('Jaffary'),
    Station('Croix Daurade'),
    Station('Lycée Raymond Naves'),
    Station('Luchet'),
    Station('Théodore de Banville'),
    Station('Atlanta'),
    Station('Saint-Caprais'),
    Station('Bayonne'),
    Station('Centre Commercial L\'Union'),
    Station('L\'Union Grande Halle'),
  ),

  // ==================== SNCF ====================
  Line(
    LineType.OVERGROUND,
    'C',
    { shape: 'square', background: '#FAB136' },
    Station('Saint-Cyprien Arènes', null, WalkTo('Arènes')),
    Station('Le TOEC'),
    Station('Lardenne'),
    Station('Saint-Martin-du-Touch'),
    Station('Ramassiers'),
    Station('Colomiers Gare SNCF'),
  ),

  // ==================== NAVETTES ====================
  Line(
    LineType.BUS,
    'Navette Aéroport',
    {
      shape: 'square',
      background: '#FCB338',
      icon: (
        <FontAwesomeIcon
          icon={faPlane}
          style={{ transformOrigin: 'center', transform: 'rotate(-25deg)' }}
        />
      ),
    },
    Station('Aéroport'),
    Station('Pont du Béarnais'),
    Station('Compans-Caffarelli'),
    Station('Jeanne d\'Arc'),
    Station('Matabiau Gare SNCF', null, WalkTo('Marengo SNCF')),
    Station('Gare Routière'),
  ),

  Line(
    LineType.BUS,
    'Navette Cimetières',
    {
      shape: 'square',
      background: '#0098D0',
      icon: <Cemetery />,
    },
    Station('Jolimont'),
    Station('Porte du Milieu'),
    Station('Porte de Caillibens'),
    Station('Jolimont'),
    Station('Marengo SNCF', null, WalkTo('Matabiau Gare SNCF')),
    Station('Jeanne d\'Arc'),
    Station('Canal du Midi'),
    Station('ZAC Ponts Jumeaux'),
    Station('Oratoire'),
    Station('Cimetière Cornebarrieu'),
    Station('Accueil Cimetière'),
    Station('Crématorium'),
    Station('Secteur I'),
    Station('Secteur G'),
    Station('Secteur F'),
    Station('Secteur D et E'),
    Station('Secteur B et C'),
    Station('Secteur A'),
    Station('Cimetière Cornebarrieu'),
  ),

  Line(
    LineType.BUS,
    'Noctambus',
    {
      shape: 'square',
      background: '#E31843',
      icon: <FontAwesomeIcon icon={faMoon} />,
      skipConnections: true,
    },
    Station('Marengo SNCF', null, WalkTo('Matabiau Gare SNCF')),
    Station('Bachelier'),
    Station('Jean Jaurès'),
    Station('Jeanne d\'Arc'),
    Station('Concorde'),
    Station('Compans-Caffarelli'),
    Station('Leclerc'),
    Station('Amidonners'),
    Station('Les Abattoirs'),
    Station('Saint-Cyprien République'),
    Station('Fer à Cheval'),
    Station('Cours Dillon'),
    Station('Pont Neuf'),
    Station('Esquirol'),
    Station('Carmes'),
    Station('Salin-Parlement'),
    Station('Palais de Justice'),
    Station('Notre Dame'),
    Station('Saint-Michel Marcel Langer'),
    Station('Récollets Daste'),
    Station('Camille Soula'),
    Station('Récollets'),
    Station('Saint-Agne SNCF'),
    Station('Delmas'),
    Station('Libellules'),
    Station('Pélude'),
    Station('Faculté de Pharmacie'),
    Station('Fac Dentaire'),
    Station('Université Paul Sabatier'),
    Station('Clotasses'),
    Station('Ramonville'),
  ),

  Line(
    LineType.BUS,
    'Navette Stadium',
    {
      shape: 'square',
      background: '#A58AC0',
      icon: <FontAwesomeIcon icon={faFutbol} />,
    },
    Station('Arènes', null, WalkTo('Saint-Cyprien Arènes')),
    Station('Stadium'),
  ),

  Line(
    LineType.BUS,
    'Navette Centre Ville',
    {
      shape: 'square',
      background: '#E875A4',
      icon: <CroixOccitane />,
    },
    Station('Cours Dillon'),
    Station('Pont Neuf'),
    Station('Brunière'),
    Station('Féral'),
    Station('Carmes'),
    Station('Trois Banquets'),
    Station('Jean Jaurès'),
    Station('Bellegarde'),
    Station('Rémusat'),
    Station('Saint-Sernin'),
    Station('Embarthe'),
    Station('Arsenal'),
    Station('Barcelone'),
    Station('Quai Saint-Pierre'),
    Station('Quai de la Daurade'),
    Station('Cours Dillon'),
  ),

  Line(
    LineType.BUS,
    'Navette Stade Ernest Wallon',
    {
      shape: 'square',
      background: '#DE0025',
      icon: <FontAwesomeIcon icon={faFootballBall} />,
    },
    Station('Barrière de Paris'),
    Station('Stade Ernest Wallon'),
  ),

  Line(
    LineType.BUS,
    'Navette Zénith',
    {
      shape: 'square',
      background: '#007B55',
      icon: <FontAwesomeIcon icon={faMicrophoneAlt} />,
    },
    Station('Arènes', null, WalkTo('Saint-Cyprien Arènes')),
    Station('Zénith'),
  ),
);
